### ISSUE TITLE
how to publish the docs?

### ISSUE THREAD

**Issue by jrmlhermitte** [NSLS-II/GeRM#24]
How should we publish these docs? With nsls-ii.github.io (I think can be done by adding [here](https://github.com/NSLS-II/docs/blob/master/requirements.txt) )?
Or on its own?

I'm not very familar with this, but I'd like to start testing seeing docs rendered on a public page.
Currently is in a long PR #23

**Comment by danielballan** [comment]
[This is basically it](https://nsls-ii.github.io/scientific-python-cookiecutter/publishing-docs.html) but we use some extra command line arguments to doctr. See bluesky for an example.

**Comment by jrmlhermitte** [comment]
Another question I have is where should I place it?
we probably don't want it to appear in the TOC for nsls-ii.github.io?
I assume it will be:
http://nsls-ii.github.io/GeRM
but not in the TOC of the main landing page.  Is that correct?

note i havent read this yet, just wanted ot be sure that this is possible to a high level.

**Comment by danielballan** [comment]
Yep, that's correct.

**Comment by jrmlhermitte** [comment]
attempt [here](https://github.com/NSLS-II/GeRM/pull/23/commits/0a3c3f384b40dd384cbf5e2fbdd797e601da931e)
